// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfNB11IXCidi8rXo_c39jw2ptvMF7M7Ng',
    appId: '1:838309131648:ios:5a20563d584927ceb97d65',
    messagingSenderId: '838309131648',
    projectId: 'jobs-creator',
    storageBucket: 'jobs-creator.appspot.com',
    iosBundleId: 'com.example.jobsCreator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfNB11IXCidi8rXo_c39jw2ptvMF7M7Ng',
    appId: '1:838309131648:ios:5a20563d584927ceb97d65',
    messagingSenderId: '838309131648',
    projectId: 'jobs-creator',
    storageBucket: 'jobs-creator.appspot.com',
    iosBundleId: 'com.example.jobsCreator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuUHokXtLZBzES3HKR5DKCuHWe2c4Lrsw',
    appId: '1:838309131648:web:3579cd72ed3485d4b97d65',
    messagingSenderId: '838309131648',
    projectId: 'jobs-creator',
    authDomain: 'jobs-creator.firebaseapp.com',
    storageBucket: 'jobs-creator.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuUHokXtLZBzES3HKR5DKCuHWe2c4Lrsw',
    appId: '1:838309131648:web:3579cd72ed3485d4b97d65',
    messagingSenderId: '838309131648',
    projectId: 'jobs-creator',
    authDomain: 'jobs-creator.firebaseapp.com',
    storageBucket: 'jobs-creator.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeH4VloFFUy0o86Cmld_red5itkdSUHXo',
    appId: '1:838309131648:android:5e97cfc96a44d799b97d65',
    messagingSenderId: '838309131648',
    projectId: 'jobs-creator',
    storageBucket: 'jobs-creator.appspot.com',
  );

}